---
name: Enhancement
description: Suggest an idea for this project
title: "[ENHANCEMENT] <title>"
labels: [enhancement]
assignees: "snoopy82481"
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Description
      description: Describe the enhancement or feature request in detail, including the problem it solves or the value it adds.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: Present a clear proposal for the enhancement, outlining the expected behavior and any implementation details if available.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
      description:  If applicable, suggest alternative solutions or approaches for achieving the desired outcome.
    validations:
      required: false
